package com.example.screentranslator

import android.graphics.Bitmap
import android.graphics.Color
import com.google.mlkit.vision.text.Text.Line
import com.google.mlkit.vision.text.Text.TextBlock
import kotlin.math.abs
import kotlin.math.roundToInt

/** Converts ML Kit paragraph/line geometry into rendering geometry for the Manual overlay. */
object TextLayoutAnalyzer {
    enum class WritingOrientation { HORIZONTAL, VERTICAL }
    data class Result(val left:Int,val top:Int,val right:Int,val bottom:Int,val sourceTextSizePx:Float,val backgroundColor:Int,val orientation:WritingOrientation=WritingOrientation.HORIZONTAL)
    fun isVerticalLine(line:Line):Boolean{val box=line.boundingBox?:return false;if(box.width()<=0||box.height()<=0)return false;val ratio=box.height().toFloat()/box.width().toFloat();if(ratio<1.30f)return false;val e=line.elements.mapNotNull{it.boundingBox}.filter{it.width()>0&&it.height()>0};if(e.size<2)return ratio>=1.55f;val v=e.zipWithNext().count{(a,b)->abs(b.centerX()-a.centerX())<=box.width()*0.75f&&b.centerY()>=a.centerY()-box.height()*0.08f};val h=e.zipWithNext().count{(a,b)->abs(b.centerY()-a.centerY())<=box.height()*0.12f&&b.centerX()>=a.centerX()-box.width()*0.08f};return v>=h}
    fun isVerticalBlock(block:TextBlock):Boolean{val l=block.lines;if(l.isEmpty())return false;val v=l.count(::isVerticalLine);return v>0&&(l.size==1||v.toFloat()/l.size>=0.5f)}
    fun verticalBlockText(block:TextBlock):String=block.lines.filter{it.text.isNotBlank()}.sortedByDescending{it.boundingBox?.centerX()?:0}.joinToString(""){it.text.trim()}.trim()
    fun shouldTreatAsParagraph(block:TextBlock):Boolean{if(isVerticalBlock(block))return false;val l=block.lines;if(l.size<2)return false;val b=l.mapNotNull{it.boundingBox}.filter{it.width()>0&&it.height()>0};if(b.size<2)return false;val mh=b.map{it.height()}.sorted()[b.size/2].toFloat().coerceAtLeast(1f);val g=b.sortedBy{it.top}.zipWithNext().map{(a,c)->(c.top-a.bottom).coerceAtLeast(0)};val compact=(g.takeIf{it.isNotEmpty()}?.sorted()?.let{it[it.size/2]}?.toFloat()?:0f)<=mh*0.65f;val lm=b.map{it.left.toFloat()}.average().toFloat();val aligned=b.map{abs(it.left-lm)}.average().toFloat()<=mh*0.85f;val text=block.text.trim();val chars=text.count{!it.isWhitespace()};if(chars<30)return false;val dr=text.count{it.isDigit()}.toFloat()/chars.coerceAtLeast(1);val terminal=l.count{val s=it.text.trimEnd();s.endsWith("。")||s.endsWith("！")||s.endsWith("？")||s.endsWith(".")||s.endsWith("!")||s.endsWith("?")};val p=l.mapNotNull{it.text.trim().takeIf{s->s.length>=4}?.take(6)};val repeated=p.groupingBy{it}.eachCount().values.any{it>=2};val w=b.map{it.width().toFloat()};val wm=w.average().toFloat().coerceAtLeast(1f);var score=0;if(compact)score++;if(aligned)score++;if(chars>=45)score++;if(terminal<=l.size/2)score++;if(dr<0.18f)score++;if(w.map{abs(it-wm)}.average()/wm<0.10f)score--;if(repeated)score-=2;if(dr>=0.28f)score-=2;return score>=3}
    fun analyze(bitmap:Bitmap,block:TextBlock):Result?{val box=block.boundingBox?:return null;if(box.width()<=0||box.height()<=0)return null;val hs=block.lines.flatMap{it.elements.mapNotNull{e->e.boundingBox?.height()?.takeIf{h->h>0}}};val glyph=if(hs.isNotEmpty())hs.sorted()[hs.size/2].toFloat()else box.height().toFloat()/block.lines.size.coerceAtLeast(1);return build(bitmap,box.left,box.top,box.right,box.bottom,glyph,if(isVerticalBlock(block))WritingOrientation.VERTICAL else WritingOrientation.HORIZONTAL)}
    fun analyze(bitmap:Bitmap,line:Line):Result?{val box=line.boundingBox?:return null;if(box.width()<=0||box.height()<=0)return null;val hs=line.elements.mapNotNull{it.boundingBox?.height()?.takeIf{h->h>0}};val glyph=if(hs.isNotEmpty())hs.sorted()[hs.size/2].toFloat()else box.height().toFloat();return build(bitmap,box.left,box.top,box.right,box.bottom,glyph,if(isVerticalLine(line))WritingOrientation.VERTICAL else WritingOrientation.HORIZONTAL)}
    private fun build(bitmap:Bitmap,l:Int,t:Int,r:Int,b:Int,glyph:Float,o:WritingOrientation):Result{val hp=(glyph*.20f).roundToInt().coerceIn(3,18);val vp=(glyph*.18f).roundToInt().coerceIn(2,12);val left=(l-hp).coerceIn(0,bitmap.width-1);val top=(t-vp).coerceIn(0,bitmap.height-1);val right=(r+hp).coerceIn(left+1,bitmap.width);val bottom=(b+vp).coerceIn(top+1,bitmap.height);return Result(left,top,right,bottom,(glyph*1.15f).coerceIn(8f,96f),estimate(bitmap,left,top,right,bottom),o)}
    private fun estimate(bitmap:Bitmap,left:Int,top:Int,right:Int,bottom:Int):Int{val s=ArrayList<Int>(64);val sx=((right-left)/12).coerceAtLeast(1);val sy=((bottom-top)/6).coerceAtLeast(1);for(x in left until right step sx){if(top>0)s.add(bitmap.getPixel(x.coerceIn(0,bitmap.width-1),(top-1).coerceIn(0,bitmap.height-1)));if(bottom<bitmap.height)s.add(bitmap.getPixel(x.coerceIn(0,bitmap.width-1),bottom.coerceIn(0,bitmap.height-1)))};for(y in top until bottom step sy){if(left>0)s.add(bitmap.getPixel((left-1).coerceIn(0,bitmap.width-1),y.coerceIn(0,bitmap.height-1)));if(right<bitmap.width)s.add(bitmap.getPixel(right.coerceIn(0,bitmap.width-1),y.coerceIn(0,bitmap.height-1)))};if(s.isEmpty())return Color.BLACK;val rs=s.map(Color::red).sorted();val gs=s.map(Color::green).sorted();val bs=s.map(Color::blue).sorted();val m=s.size/2;return Color.rgb(rs[m],gs[m],bs[m])}
}
